---
title: "git_00"
author: "Racheal Adeneye"
date: "Year 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A Mother's breast:  
Safe refuge from her childish fears,  
From childish troubles, childish tears,  
Mists that enshroud her dawning years!  
see how in sleep she seems to sing  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
There's a patch of old snow in a corner  
That I should have guessed  
Was a blow-away paper the rain  
Had brought to rest.  
  
It is speckled with grime as if  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
A trusting little leaf of green,  
A bold audacious frost;  
A rendezvous, a kiss or two,  
And youth for ever lost.  
Ah, me!  
The bitter, bitter cost.  
  
A flaunting patch of vivid red,  
That quivers in the sun;  
A windy gust, a grave of dust,  
The little race is run.  
Ah, me!  
Were that the only one.  
